### PR TITLE
get updated client info from db

### LINKED ISSUE #47: Editing the registration form's gender field is not reflected in the FP Visit form
Steps to replicate:

- Register a new client, and put gender = other (biological sex can be either female or male)
- Start a new FP visit and go to the client history page. The method at intake is not displayed (this is a known issue and being addressed separately).
- Exit the FP visit without submitting
- Re-open the registration form and edit the person's gender from "other" to "female"
- Save the reg form and then start a new FP visit form.
- The gender edit does not reflect in the FP Visit form, because the method at intake question is still missing in the Client History page.

### PR DESCRIPTION
**Pull request by owais-vd**
bug fixed #47

### CODE REVIEW

**Review by paulinembabu — COMMENTED** [review]
Kindly fix the Failing Travis issue on this PR

**Comment by owais-vd** [comment]
Codacy not showing any issue in this PR report could you mark if you found any.

**Comment by dubdabasoduba** [comment]
> Kindly fix the Failing Codacy on this PR

@paulinembabu  Do you mean travis? If so @syedowaisali90 please remove the databinding snippet from  the reference-app grade file. 
```
dataBinding {
        enabled = true
    }

```

**Comment by owais-vd** [comment]
data-binding removed

**Review by paulinembabu — APPROVED** [review]

**Pull request merged**
